#!/bin/zsh

[[ -d /etc/pacman.d/hooks ]] || sudo mkdir /etc/pacman.d/hooks
sudo cp ./blender_filmic.hook /etc/pacman.d/hooks/blender_filmic.hook
sudo cp ./blender_filmic.zsh /etc/pacman.d/hooks/blender_filmic.zsh
