#!/bin/sh

[ -d /etc/pacman.d/hooks ] || ( sudo mkdir /etc/pacman.d/hooks && echo "created /etc/pacman.d/hooks" )
sudo cp ./blender_filmic.hook /etc/pacman.d/hooks/blender_filmic.hook 
sudo cp ./blender_filmic.sh /etc/pacman.d/hooks/blender_filmic.sh
echo "SUCCESS"

